query MyConversations {
  myConversations {
    id
    participant1Id
    participant1 {
      id
      email
      profile {
        firstName
        lastName
        pictureUrl
      }
      subscriptions {
        id
        plan
        status
        endDate
      }
    }
    participant2Id
    participant2 {
      id
      email
      profile {
        firstName
        lastName
        pictureUrl
      }
      subscriptions {
        id
        plan
        status
        endDate
      }
    }
    propertyId
    lastMessageAt
    createdAt
    messages {
      id
      content
      senderId
      createdAt
      readAt
    }
  }
}

query ConversationMessages($conversationId: String!) {
  conversationMessages(conversationId: $conversationId) {
    id
    conversationId
    senderId
    sender {
      id
      email
      profile {
        firstName
        lastName
        pictureUrl
      }
      subscriptions {
        id
        plan
        status
        endDate
      }
    }
    receiverId
    receiver {
      id
      email
      profile {
        firstName
        lastName
        pictureUrl
      }
      subscriptions {
        id
        plan
        status
        endDate
      }
    }
    propertyId
    content
    status
    readAt
    createdAt
  }
}
